apiVersion: v1
kind: Pod
metadata:
  name: pod-one
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-two
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-three
  labels:
    app: broken
spec:
  containers:
    - name: failbox
      image: busybox
      command: ["/bin/sh", "-c", "exit 1"]
